model:
  LINEAR: False
  SPLIT: linear
  COMP: concatenate
  TREE_DEPTH: 4
  MLP_LAYERS: 5
  DROPOUT: 0.07041761417608994

training:
  SEEDS: [1225, 1337, 2020, 6021991] 
  LR: 0.001
  EPOCHS: 100
  BATCH_SIZE: 512 
  REG: 1.4837286400170702
  WORKERS: 16

DATA_NAME: "CLICK"